### ISSUE TITLE
where to get the COCO_train2014_000000152328.jpg？

### ISSUE THREAD

**Issue by gotope** [karpathy/neuraltalk2#103]
hello, I got a problem when train the MSCOCO:
python prepro.py --input_json coco/coco_raw.json --num_val 5000 --num_test 5000 --images_root coco/images --word_count_threshold 5 --output_json coco/cocotalk.json --output_h5 coco/cocotalk.h5
...
...
inserting the special UNK token
assigned 5000 to val, 5000 to test.
encoded captions to array of size  (616767, 16)
Traceback (most recent call last):
 IOError: [Errno 2] No such file or directory: u'coco/images/train2014/COCO_train2014_000000152328.jpg'
 
-------------------------------
I checked the ipython output, there are always a unexpected character  u',

# lets see what they look like
print out[0]

{'captions': [u'A man with a red helmet on a small moped on a dirt road. ', u'Man riding a motor bike on a dirt road on the countryside.', u'A man riding on the back of a motorcycle.', u'A dirt path with a young person on a motor bike rests to the foreground of a verdant area with a bridge and a background of cloud-wreathed mountains. ', u'A man in a red shirt and a red hat is on a motorcycle on a hill side.'], 'file_path': u'val2014/COCO_val2014_000000391895.jpg', 'id': 391895}

**Comment by cjds** [comment]
One way to do it is to just download the images from [here](http://mscoco.org/dataset/#download) and then unzipping them in the images directory

**Comment by gotope** [comment]
@cjds  OK. thanks.

**Comment by carsonDB** [comment]
every string headed with 'u' means it is encoded as an unicode string. In python, it is safer to use it.

**Comment by gotope** [comment]
@carsonDB 
that's helpful. thanks

**Comment by serser** [comment]
download from http://images.cocodataset.org/train2014/COCO_train2014_000000152328.jpg
