### ISSUE TITLE
Can't evaluate BLEU/METEOR/CIDEr scores

### ISSUE THREAD

**Issue by y657250418** [karpathy/neuraltalk2#104]
When I use the command:

th eval.lua -model /home/yh/checkpoint/model_id1-501-1448236541.t7 -image_folder /home/yh/mscoco/test2015 -num_images -1 -language_eval 1

it displays after generating image description :

evaluating performance... 0/-1 (0.000000)
loading annotations into memory...
0:00:00.772656
creating index...
Traceback (most recent call last):
  File "myeval.py", line 17, in <module>
    coco = COCO(annFile)
  File "/mnt/disk1/yh/neuraltalk2/neuraltalk2-master/coco-caption/pycocotools/coco.py", line 76, in __init__
    self.createIndex()
  File "/mnt/disk1/yh/neuraltalk2/neuraltalk2-master/coco-caption/pycocotools/coco.py", line 93, in createIndex
    if self.dataset['type'] == 'instances':
KeyError: 'type'
/home/wonglab/torch/install/bin/luajit: ./misc/utils.lua:17: attempt to index local 'file' (a nil value)
stack traceback:
	./misc/utils.lua:17: in function 'read_json'
	./misc/net_utils.lua:202: in function 'language_eval'
	eval.lua:167: in function 'eval_split'
	eval.lua:173: in main chunk
	[C]: in function 'dofile'
	...glab/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

Who can help me ?

**Comment by y657250418** [comment]
I used the wrong captions_val2014.json file.

The question has been solved.

**Comment by pangjh3** [comment]
cap = dset.CocoCaptions(root='../Data_zoo/COCO/train2014',
                        annFile='../Data_zoo/COCO/annotations/captions_train2014.json',
                        transform=transforms.ToTensor(), target_transform=transforms.ToTensor)
print('Number of samples: ', len(cap))
img, target = cap[3]  # load 4th sample
print("Image Size: ", img.size())
print(target)

I run this code but still have the problem:
![image](https://user-images.githubusercontent.com/16623530/33835858-bf77c4ce-dec2-11e7-968e-51a266642d0c.png)

Who can help?

**Comment by pangjh3** [comment]
Problem finished. Just use the latest COCO API https://github.com/tylin/coco-caption

**Comment by jamiechoi1995** [comment]
@SkyFlyboy I met the same issue, but my COCO API is the latest https://github.com/tylin/coco-caption

How did you solve the problem? Just simply use the lastest COCO API?

Thanks.

**Comment by MozhdehDokhani** [comment]
>  been solved.

How did you solve it? I have this error:
`Loading and preparing results...     
Traceback (most recent call last):
  File "myeval.py", line 29, in <module>
    cocoRes = coco.loadRes(resFile)
  File "/home/mozhdeh/Documents/neuraltalk2-master/coco-caption/pycocotools/coco.py", line 280, in loadRes
    if 'caption' in anns[0]:
IndexError: list index out of range
/home/mozhdeh/torch/install/bin/luajit: ./misc/utils.lua:17: attempt to index local 'file' (a nil value)
stack traceback:
	./misc/utils.lua:17: in function 'read_json'
	./misc/net_utils.lua:202: in function 'language_eval'
	eval.lua:167: in function 'eval_split'
	eval.lua:173: in main chunk
	[C]: in function 'dofile'
	...hdeh/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x556c329a1570
`

**Comment by mymuli** [comment]
我知道怎么解决了.... 在eval阶段，设置命令-language_eval 0....如果-language_eval  1, 会报错：    if 'caption' in anns[0]:
IndexError: list index out of range
