### ISSUE TITLE
prepro.py: Image file not found

### ISSUE THREAD

**Issue by AdityaChaganti** [karpathy/neuraltalk2#131]
Hello,

After running coco_preprocess which returns a combined list of train/val data consisting of annotations and file paths mapped by image IDs, I proceed to execute the prepro.py script, at which point I run into the following error:

python prepro.py --input_json coco_raw.json --num_val 5000 --num_test 5000 --images_root images --word_count_threshold 5 --output_json cocotalk.json --output_h5 cocotalk.h5
parsed input parameters:
{
  "output_json": "cocotalk.json", 
  "images_root": "images", 
  "input_json": "coco_raw.json", 
  "word_count_threshold": 5, 
  "max_length": 16, 
  "output_h5": "cocotalk.h5", 
  "num_test": 5000, 
  "num_val": 5000
}
example processed tokens:
['a', 'woman', 'riding', 'a', 'bike', 'down', 'a', 'bike', 'trail']
['a', 'man', 'sits', 'in', 'a', 'recliner', 'with', 'his', 'laptop']
***truncated for conciseness***
top words and their counts:
(1019751, 'a')
(224731, 'on')
(212678, 'of')
***truncated for conciseness***
total words: 6447836
number of bad words: 20059/29625 = 67.71%
number of words in vocab would be 9566
number of UNKs: 34543/6447836 = 0.54%
max length sentence in raw data:  49
sentence length distribution (count, number of words):
 0:          0   0.000000%
 1:          0   0.000000%
 2:          0   0.000000%
 3:          0   0.000000%
 4:          0   0.000000%
 5:          1   0.000162%
 6:         15   0.002432%
 7:       4935   0.800140%
 ***.....49 other entries truncated for conciseness***

inserting the special UNK token
assigned 5000 to val, 5000 to test.
encoded captions to array of size  (616767, 16)
Traceback (most recent call last):
  File "prepro.py", line 211, in <module>
    main(params)
  File "prepro.py", line 155, in main
    I = imread(os.path.join(params['images_root'], img['file_path']))
  File "/opt/anaconda/lib/python2.7/site-packages/scipy/misc/pilutil.py", line 154, in imread
    im = Image.open(name)
  File "/opt/anaconda/lib/python2.7/site-packages/PIL/Image.py", line 2272, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: u'images/train2014/COCO_train2014_000000152328.jpg'

Am I missing something?

**Comment by cuongduc** [comment]
@AdityaChaganti That file is missed from COCO dataset. There are several issues on this problem in the issue list. You can take a look at them for solution

**Comment by AdityaChaganti** [comment]
@cuongduc Just [download](http://mscoco.org/dataset/#download) and unzip them, then?

**Comment by AdityaChaganti** [comment]
Got it. Thanks!
