### ISSUE TITLE
train.lua: misc.utils not found: No LuaRocks module found for misc.utils

### ISSUE THREAD

**Issue by AdityaChaganti** [karpathy/neuraltalk2#132]
Hey,

I'm trying to train my own model on the COCO dataset (And hopefully other datasets soon), and I am using an EC2 CPU instance. 

When I run "th train.lua -input_h5 coco/cocotalk.h5 -input_json coco/cocotalk.json -gpuid -1", I run into the following issue:

/home/adityac/torch/install/bin/luajit: /home/adityac/torch/install/share/lua/5.1/trepl/init.lua:384: module 'misc.utils' not found:No LuaRocks module found for misc.utils
	no field package.preload['misc.utils']
	no file '/home/adityac/.luarocks/share/lua/5.1/misc/utils.lua'
	no file '/home/adityac/.luarocks/share/lua/5.1/misc/utils/init.lua'
	no file '/home/adityac/torch/install/share/lua/5.1/misc/utils.lua'
	no file '/home/adityac/torch/install/share/lua/5.1/misc/utils/init.lua'
	no file './misc/utils.lua'
	no file '/home/adityac/torch/install/share/luajit-2.1.0-beta1/misc/utils.lua'
	no file '/usr/local/share/lua/5.1/misc/utils.lua'
	no file '/usr/local/share/lua/5.1/misc/utils/init.lua'
	no file '/home/adityac/.luarocks/lib/lua/5.1/misc/utils.so'
	no file '/home/adityac/torch/install/lib/lua/5.1/misc/utils.so'
	no file '/home/adityac/torch/install/lib/misc/utils.so'
	no file './misc/utils.so'
	no file '/usr/local/lib/lua/5.1/misc/utils.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/home/adityac/.luarocks/lib/lua/5.1/misc.so'
	no file '/home/adityac/torch/install/lib/lua/5.1/misc.so'
	no file '/home/adityac/torch/install/lib/misc.so'
	no file './misc.so'
	no file '/usr/local/lib/lua/5.1/misc.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'error'
	/home/adityac/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
	train.lua:8: in main chunk
	[C]: in function 'dofile'
	...tyac/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x004064d0

I'm not entirely sure how to address this. Any help?

**Comment by Subhankari** [comment]
Hi

I am getting the same error. How did you solve it?

Appreciate your help.

**Comment by achag-spec** [comment]
@Subhankari 

cd'ing into the project directory before running this should work. It likely isn't picking up the [local file](https://github.com/karpathy/neuraltalk2/blob/master/misc/utils.lua).
