### ISSUE TITLE
How long does CPU based training take?

### ISSUE THREAD

**Issue by AdityaChaganti** [karpathy/neuraltalk2#135]
I'm trying to figure out how long it would take to train the model on MS COCO, running it on a CPU instance. Has anyone managed to train on a CPU to a point where the validation error was sufficiently low? How long did that take?

**Comment by cjds** [comment]
I've done this. It took about 2 days for me.

**Comment by AdityaChaganti** [comment]
@cjds Weird. I've been at it for a day, and it's evaluating 2272/3200 of the split right now. I'm assuming that it's the first split, still, given the speed at which it's been going all day. It was at 1400/3200 8 hours back. 

My screen session that I left running overnight didn't log on terminal beyond a point when I scroll up, but again, I'm assuming that this is the first split given the speed. I was under the impression that the batched data implementation runs through multiple splits of 3200 images and annotations before it gets to the 70,000 iteration mark, at which point the loss/CiDer score is supposed to be acceptable. I currently have a loss of 9.17, and it seems to be reducing only marginally. 

Is my conclusion that training is very slow for some reason correct, or am I missing something conceptually here?

**Comment by cjds** [comment]
That loss seems rather high from my memory. This was a while back. I did leave it running for 48 hours straight (not only one night). But I remember clearly the loss steadily decreasing

**Comment by AdityaChaganti** [comment]
Moved to a GPU instance, and everything went okay. The CPU was really, really slow. Would have taken an year to train.
