### ISSUE TITLE
Necessary to clone LSTM for every time step?

### ISSUE THREAD

**Issue by chaonan99** [karpathy/neuraltalk2#136]
I've notice that the script makes a clone of `self.core` for every time step and save them into `self.clones` in `LanguageModel.lua`. Is it necessary to do so? Why not just `self.core:forward(...)` and `self.core:backward()`?

**Comment by karpathy** [comment]
hi, it's because you have to save the activations at each time step to do backprop through time. the clone modules have to "remember" these in their instance variables.
