### ISSUE TITLE
how to generate multiple captions?

### ISSUE THREAD

**Issue by shinandrew** [karpathy/neuraltalk2#146]
Is there a way to generate multiple captions, kind of in n-best manner?

I've tried to tweak the protos.lm:sample part, but couldn't figure out..

**Comment by spizler** [comment]
Did you find a way to do this? I would be interested in your (or anyone else's) solution if you did. Thanks!

**Comment by xwasco** [comment]
Hi all, I am interested too... anyone succeeded?
