### ISSUE TITLE
read error: read 0 blocks instead of 1

### ISSUE THREAD

**Issue by kevindesai777** [karpathy/neuraltalk2#16]
I ran this line of code to predict caption on some images. 
th eval.lua -model /home/ubuntu/neuraltalk2/model/ -image_folder ./images/ -num_images 1
Using AWS server configured with Torch and Caffe. 
Tried with mentioning the name of the model also. 
/home/ubuntu/torch-distro/install/bin/luajit: ...ubuntu/torch-distro/install/share/lua/5.1/torch/File.lua:194: read error: read 0 blocks instead of 1 at /home/ubuntu/torch-distro/pkg/torch/lib/TH/THDiskFile.c:302
stack traceback:
	[C]: in function 'readInt'
	...ubuntu/torch-distro/install/share/lua/5.1/torch/File.lua:194: in function 'readObject'
	...ubuntu/torch-distro/install/share/lua/5.1/torch/File.lua:294: in function 'load'
	eval.lua:68: in main chunk
	[C]: in function 'dofile'
	...rch-distro/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
	[C]: at 0x00406670

Getting this error and have little idea of what this means.

**Comment by karpathy** [comment]
You're not passing it the model correctly. It expects exact path to it, not just the folder that holds it.

**Comment by kevindesai777** [comment]
Alright, I did that. I get another error.

/home/ubuntu/torch-distro/install/bin/luajit: ...ubuntu/torch-distro/install/share/lua/5.1/torch/File.lua:277: unknown object
stack traceback:
	[C]: in function 'error'
	...ubuntu/torch-distro/install/share/lua/5.1/torch/File.lua:277: in function 'readObject'
	...ubuntu/torch-distro/install/share/lua/5.1/torch/File.lua:271: in function 'readObject'
	...ubuntu/torch-distro/install/share/lua/5.1/torch/File.lua:257: in function 'readObject'
	...ubuntu/torch-distro/install/share/lua/5.1/torch/File.lua:271: in function 'readObject'
	...ubuntu/torch-distro/install/share/lua/5.1/torch/File.lua:271: in function 'readObject'
	...ubuntu/torch-distro/install/share/lua/5.1/torch/File.lua:257: in function 'readObject'
	...ubuntu/torch-distro/install/share/lua/5.1/torch/File.lua:271: in function 'readObject'
	...ubuntu/torch-distro/install/share/lua/5.1/torch/File.lua:271: in function 'readObject'
	...ubuntu/torch-distro/install/share/lua/5.1/torch/File.lua:294: in function 'load'
	eval.lua:68: in main chunk
	[C]: in function 'dofile'
	...rch-distro/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
	[C]: at 0x00406670
