### ISSUE TITLE
Loadcaffe model not loading

### ISSUE THREAD

**Issue by Akito82** [karpathy/neuraltalk2#167]
Hi,
if I do th train.lua ..., the following error occurs:
Couldn't load model/VGG_ILSVRC_16_layers.caffemodel

I read that the reason could be a corrupt loadcaffe file, but so far reinstalling didn't do anything for me. 
Any ideas? 
Thanks

**Comment by karthiknvlr** [comment]
check whether you had give a correct path for the model file 
In my case it will be like 
--model /home/karthikn/neuraltalk2/model/VGG_ILSVRC_16_layers.caffemodel

**Comment by Akito82** [comment]
Thank you very much, that was it.
