### ISSUE TITLE
eval_split

### ISSUE THREAD

**Issue by AlaaHassanAli** [karpathy/neuraltalk2#173]
when i train this error appers : 
DataLoader loading json file: coco/cocotalk.json
vocab size is 8102
DataLoader loading h5 file: coco/cocotalk.h5
read 82783 images of size 3x256x256
max sequence length in data is 16
assigned 82783 images to split train
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:537] Reading dangerously large protocol message. If the message turns out to be l
arger than 1073741824 bytes, parsing will be halted for security reasons. To increase the limit (or to disable these warnings), see Coded
InputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 553432081
Successfully loaded model/VGG_ILSVRC_16_layers.caffemodel
conv1_1: 64 3 3 3
conv1_2: 64 64 3 3
conv2_1: 128 64 3 3
conv2_2: 128 128 3 3
conv3_1: 256 128 3 3
conv3_2: 256 256 3 3
conv3_3: 256 256 3 3
conv4_1: 512 256 3 3
conv4_2: 512 512 3 3
conv4_3: 512 512 3 3
conv5_1: 512 512 3 3
conv5_2: 512 512 3 3
conv5_3: 512 512 3 3
fc6: 1 1 25088 4096
fc7: 1 1 4096 4096
fc8: 1 1 4096 1000
converting first layer conv filters from BGR to RGB...
total number of parameters in LM: 11455399
total number of parameters in CNN: 136358208
constructing clones inside the LanguageModel
iter 0: 9.027307
/root/torch/install/bin/luajit: ./misc/DataLoader.lua:84: split val not found.
stack traceback:
[C]: in function 'assert'
./misc/DataLoader.lua:84: in function 'getBatch'
train_new.lua:196: in function 'eval_split'
train_new.lua:321: in main chunk
[C]: in function 'dofile'
/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
[C]: at 0x00405d50

any help ?? (note : in preprocessing i put num of val & test images =0)

**Comment by j2233ack** [comment]
Hi
Did you solve the problem?
I met the same problem as you.

**Comment by AlaaHassanAli** [comment]
yes , by not making num of val & test images =0 and  make it the default (5000)
