### ISSUE TITLE
File names / file paths to the .json file?

### ISSUE THREAD

**Issue by trych** [karpathy/neuraltalk2#18]
Hi there,
would it be possible to add a "JSON only" mode? For my purposes I only really need the .json file instead of the entire html structure. And I guess that version would be the more (or most?) basic outcome for such a script.

What I imagine:
1. Run the shell command using something like eval-json.lua instead of eval.lua.
2. Images don't get renamed and don't get copied.
3. A .json file will be placed in the images folder alongside the images.
4. In the .json file an entry could look like: `{"caption":"my resulting caption","image_file":"myFilename.jpg"}`

Is this feasible / desirable? For me it would make sense as it would be a more generic result of the script.

**Comment by karpathy** [comment]
The eval script already does what you're describing. Make sure `-dump_images 0`, and `-dump_json 1`. This will create the json file inside `vis/`, and you can use that right away or you can use the html interface to visualize it.

**Comment by trych** [comment]
Thanks, that works indeed.
Any chance though to have the original filenames in the .json file instead of an image id? I would find that very useful.

**Comment by karpathy** [comment]
Can you make the `id` be the filename? I didn't want to bloat the json files too much.

**Comment by trych** [comment]
Unfortunately in the specific workflow that I am using this, I can't.
I understand that the .json files should not be bloated. Would it be a possibility though to have an option to replace the `image_id` by `image_file`? That way, you could choose yourself which one you need.

**Comment by jacopofar** [comment]
I had a similar need and made a pull request to add the dump_path flag.
It defaults to 0, producing the usual JSON, when set to 1 adds the file_path field to the JSON.

Example:

    {"file_name":"\/mounted\/Desktop\/f33d9a47-fb17-45aa-ab0f-27dd80a92951.jpg","image_id":"3","caption":"a man in a suit and tie is holding a cell phone"}

**Comment by trych** [comment]
Cool, thanks! Will use that for now. :)

**Comment by trych** [comment]
Since this was just merged, my issue is solved. Will close.
