### ISSUE TITLE
Error while running eval.lua

### ISSUE THREAD

**Issue by kevindesai777** [karpathy/neuraltalk2#19]
While evaluating images, 
```
th eval.lua -model model_id1-501-1448236541.t7 -image_folder images/ -num_images -1
```
I get this error,
```
/home/ubuntu/torch-distro/install/bin/luajit: ...ubuntu/torch-distro/install/share/lua/5.1/torch/File.lua:277: unknown object
stack traceback:
	[C]: in function 'error'
	...ubuntu/torch-distro/install/share/lua/5.1/torch/File.lua:277: in function 'readObject'
	...ubuntu/torch-distro/install/share/lua/5.1/torch/File.lua:271: in function 'readObject'
	...ubuntu/torch-distro/install/share/lua/5.1/torch/File.lua:257: in function 'readObject'
	...ubuntu/torch-distro/install/share/lua/5.1/torch/File.lua:271: in function 'readObject'
	...ubuntu/torch-distro/install/share/lua/5.1/torch/File.lua:271: in function 'readObject'
	...ubuntu/torch-distro/install/share/lua/5.1/torch/File.lua:257: in function 'readObject'
	...ubuntu/torch-distro/install/share/lua/5.1/torch/File.lua:271: in function 'readObject'
	...ubuntu/torch-distro/install/share/lua/5.1/torch/File.lua:271: in function 'readObject'
	...ubuntu/torch-distro/install/share/lua/5.1/torch/File.lua:294: in function 'load'
	eval.lua:68: in main chunk
	[C]: in function 'dofile'
	...rch-distro/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
	[C]: at 0x00406670
```
Have little clue how to solve this. Any help would be great!

**Comment by soumith** [comment]
@kevindesai777 are you on the latest torch / nn? That error sounds like your torch install cant find some newer class....

**Comment by kevindesai777** [comment]
@soumith I am using an AWS AMI which came preinstalled with Torch, CUDA, etc. Should I try updating it?

**Comment by soumith** [comment]
Yes.
luarocks install torch
luarocks install nn
luarocks install cutorch
luarocks install cunn

**Comment by kevindesai777** [comment]
I did the steps you mentioned and I am stuck with this error. I checked if cudnn is properly installed or not, and it seems good enough. 

```
/home/ubuntu/torch/install/share/lua/5.1/cudnn/ffi.lua:585: These bindings are for version 3000 or above, while the loaded CuDNN is version: 20  
Are you using an older version of CuDNN?
stack traceback:
	[C]: in function 'error'
	/home/ubuntu/torch/install/share/lua/5.1/trepl/init.lua:383: in function 'require'
	eval.lua:59: in main chunk
	[C]: in function 'dofile'
	...untu/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670
```

**Comment by soumith** [comment]
You need to download the latest version of cudnn from the website and
install it as well. The AMI is horribly out of date and is giving you all
these issues.

**Comment by kevindesai777** [comment]
Yep, done! Thanks!

**Comment by j2233ack** [comment]
I got this error,

/home/sc/torch/install/bin/luajit:/home/sc/torch/install/share/lua/5.1/trepl/init.lua:389:``**_ /home/sc/torch/install/share/lua/5.1/loadcaffe/ffi.lua:10: /home/sc/torch/install/lib/lua/5.1/libloadcaffe.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameEv
stack traceback:
	[C]: in function 'error'
	/home/sc/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	train.lua:6: in main chunk
	[C]: in function 'dofile'
	...e/sc/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50

Do you know the reason?
