### ISSUE TITLE
Live camera feed from lua-camera not working

### ISSUE THREAD

**Issue by Mithul** [karpathy/neuraltalk2#26]
Hi im using the CPU model from your Readme and  [lua-camera](https://github.com/clementfarabet/lua---camera)  to get the image from the camera to process instead of reading an image from the folder. This method always gives me 
"a view of a UNK UNK in a cloudy sky" as the caption"
I did this by 
### 1. Initializing at the start of the program 
   ```lua
   require 'camera'
   cam = image.Camera(0)
   ```
### 2. And making the following change to the eval_script function

```lua
 -- local data = loader:getBatch{batch_size = opt.batch_size, split = split, seq_per_img = opt. seq_per_img} #commented to prevent file load from folder
 img = cam:forward()
 data={images=nil,infos=nil}
 data.images=torch.ByteTensor(1, 3, img:size(2), img:size(3))
 data.images[1]=img
 ... --some lines in between
 for k=1,#sents do
   print(sents[k]) --removed everything else
 end
 break --since im using only 1 frame
 end --end loop
 ```
### 3. Loop the function

```lua
while true do
    loss, split_predictions, lang_stats = eval_split(opt.split, {num_images = opt.num_images})
end
```

### 1.  Loop the function by adding the following line

```lua
while true do
  local folder="/home/mithul/torch/projects/neuraltalk2/cam"
  local imfile=folder.."/image.jpeg"
  os.execute("streamer -f jpeg -s 1280x720 -o "..imfile)
    load_data()
    loss, split_predictions, lang_stats = eval_split(opt.split, {num_images = opt.num_images})
    print('loss: ', loss)
end
```
### 2. Run eval.lua with "/home/mithul/torch/projects/neuraltalk2/cam" as the image folder

However this method causes the camera to be switched on and off by the OS for each image causing a delay, and also re-initialize the loader for every frame.

I would like to know why the first method does not work while the second method works.

**Comment by Mithul** [comment]
The conversion from the default FloatTensor for lua-camera to ByteTensor was resulting in an all 0 Tensor(Black Image).  The following code solved it for me.
```lua
data.images[1]=(img*256)
```

**Comment by karpathy** [comment]
Awesome, thank you for the nice writeup. Does it work? Are you able to run the code on streaming camera? If so, I'd be eager to get an eval_camera PR and merge into master.
