### ISSUE TITLE
Getting error on CPU only mode

### ISSUE THREAD

**Issue by ellipticaldoor** [karpathy/neuraltalk2#28]
I followed all the tutorial for installing all the dependeces, I can´t install cutorch and cunn because I don´t have an nvidia card. I´m on OSX 10.11.1.

I downloaded the model and tried to use it like this:

```
th eval.lua -gpuid -1 -model model_id1-501-1448236541.t7_cpu.t7
```

But I get the following error:

```
DataLoader loading json file: 	/scr/r6/karpathy/cocotalk.json
/Users/miguel/torch/install/bin/luajit: ./misc/utils.lua:17: attempt to index local 'file' (a nil value)
stack traceback:
	./misc/utils.lua:17: in function 'read_json'
	./misc/DataLoader.lua:10: in function '__init'
	/Users/miguel/torch/install/share/lua/5.1/torch/init.lua:91: in function </Users/miguel/torch/install/share/lua/5.1/torch/init.lua:87>
	[C]: in function 'DataLoader'
	eval.lua:84: in main chunk
	[C]: in function 'dofile'
	...guel/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x01035bdbd0
```

What can I do?

**Comment by karpathy** [comment]
you have to provide it with an image folder you'd like to use. Otherwise it's trying to use the coco data.

**Comment by ellipticaldoor** [comment]
Sorry, now it works. I missunderstood. I thinked that this code was for the video analisis thing. I found what I wanted here https://gist.github.com/kylemcdonald/b02edbc33942a85856c8
