### ISSUE TITLE
Out of memory error when finetuning is enabled

### ISSUE THREAD

**Issue by Leftetris** [karpathy/neuraltalk2#35]
Hello, 

I am experiencing an error when I try to train a model with finetuning either from a previously saved checkpoint or from scratch.

What I did:

Stage 1 (success)
-----------------------------------------------------------------------------------------------------------
$ th train.lua -input_h5 coco/cocotalk.h5 -input_json coco/cocotalk.json -checkpoint_path chkp -language_eval 1
-----------------------------------------------------------------------------------------------------------
This trained a model on COCO with no finetuning. I got cider ~0.6 after 150k+ iters so I saved the checkpoint elsewhere (e.g. saved_checkpoints/coco_initial.t7) to continue with finetuning.

Stage 2 (failure) 
-----------------------------------------------------------------------------------------------------------
$ th train.lua -input_h5 coco/cocotalk.h5 -input_json coco/cocotalk.json -checkpoint_path chkp -language_eval 1 -finetune_cnn_after 0 -start_from saved_checkpoints/coco_initial.t7
-----------------------------------------------------------------------------------------------------------
Tried to enable finetuning and load the previously saved checkpoint, but what I got was:

-----------------------------------------------------------------------------------------------------------
wrote json checkpoint to chkp/model_id.json	
/home/cybernaut/torch/install/bin/luajit: ./misc/optim_updates.lua:65: cuda runtime error (2) : out of memory at /tmp/luarocks_cutorch-scm-1-6112/cutorch/lib/THC/THCStorage.cu:44
stack traceback:
	[C]: in function 'new'
	./misc/optim_updates.lua:65: in function 'adam'
	train.lua:387: in main chunk
	[C]: in function 'dofile'
	...naut/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
	[C]: at 0x00405e40
-----------------------------------------------------------------------------------------------------------

The GPU I used: GeForce GTX 860M with 4Gb of memory
Installed Cuda7 and cudnn R3
Installed all prementioned torch packages in readme of neuraltalk2

Any hints or ideas, would be much appreciated!
Thank you!

**Comment by karpathy** [comment]
4GB is quite little unfortunately. See if it helps to decrease the `batch_size` ? Try down to 1 to see what happens.

**Comment by Leftetris** [comment]
batch_size 4 seems to do the trick, thank you so much!

**Comment by karpathy** [comment]
Great! You might want to slightly decrease the learning rate, as a good heuristic, when decreasing the batch size. E.g. reduction by x4 => learning rate reduce ~2-4x is decent guess. Closing, thanks for creating the issue!

**Comment by Leftetris** [comment]
Thanks for the hint and for all your help.
Take care!

Στις Τρίτη, 1 Δεκεμβρίου 2015, ο χρήστης Andrej <notifications@github.com>
έγραψε:
