### ISSUE TITLE
option -start_from in train.lua : what's the expected behaviour

### ISSUE THREAD

**Issue by SaMnCo** [karpathy/neuraltalk2#47]
Hi, 

I have trained a model on the MSCOCO without any fine tuning. Then I wanted to add the fine tuning, so I did: 

   th train.lua -input_h5 /data/training/cocotalk.h5 \
        -input_json /data/training/cocotalk.json \
        -cnn_proto /data/training/VGG_ILSVRC_16_layers_deploy.prototxt \
        -cnn_model /data/training/VGG_ILSVRC_16_layers.caffemodel \
        -checkpoint_path /data/model \
        -finetune_cnn_after 0 \
        -start_from /data/model/model_id.t7 \
        -batch_size 4

(small batch size as running with 4GB vRAM only)

As a result, a new file model_id.json was created and keeps growing (I am now at about 80k iterations). 
How am I supposed to combine this new file with the original t7 file? Is it an expected behaviour?

Many thanks in advance,

**Comment by SaMnCo** [comment]
OK it was just a question of time. Now the .t7 file has evolved (it probably needs to process the 125k files first). 

Closing.

**Comment by jchoi1** [comment]
What do you mean by the .t7 file evolved? I'm trying to train a model without any fine tuning, but when the train.lua script ends, the only output is the model_id.json file.

**Comment by SaMnCo** [comment]
Right, so eventually once you have a first t7, you may want to stop
training and change some settings before you restart. You don't have to
restart from 0, but tell your train.lua that you want to incrementally
improve this reference model.
This is also useful to add new training datasets.

Then when a json reaches enough perf, it will be merged into your
start-from model.

**Comment by jchoi1** [comment]
I see. It sounds like I was just not being patient enough with the training script. About how many iterations should I expect until the first t7 shows up in the checkpoint_path? Or does that depend on my training data size?

**Comment by jchoi1** [comment]
I just got your email. For others' reference: 
"Json files are temporary / checkpoint models. When the validation of performance will be good enough, the json will be turned into a .t7, and a new "delta" model .json file will be created.
Essentially, .t7 are the results of long periods of compute, and .json are intermediate temporary models.

My first iteration to get a .t7 took more than a day on a g2.2xlarge on EC3, so I wouldn't worry unless it's been a week or so"

Thanks again!
