### ISSUE TITLE
cannot open eval.lua: No such file or directory

### ISSUE THREAD

**Issue by ShuaiW** [karpathy/neuraltalk2#63]
I've followed the setup till the cjson part (since I am only using CPU). However when I ran the following command I got the error. I am on Mac OSX 10.9.5

**command**
`$ th eval.lua -model model_id1-501-1448236541.t7_cpu.t7 -image_folder ./img -num_images 1 -gpuid -1`

**error**
`../torch/install/bin/luajit: cannot open eval.lua: No such file or directory
stack traceback:
	[C]: in function 'dofile'
	../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x0105f2a1d0`

Anyone can point me to the right direction? Thanks ;-)

**Comment by n0xi** [comment]
ShuaiW i have the same error message, did you fix it ?

**Comment by ketyi** [comment]
I also have the same. What is the fix?

**Comment by ketyi** [comment]
@n0xi You should clone the neuraltalk2 project also...

**Comment by n0xi** [comment]
Yes my dear ... i test later; thx

**Comment by Chenkunhui** [comment]
We have the same problem,could you tell me how to solve this problem?
