### ISSUE TITLE
Issue while running eval.lua

### ISSUE THREAD

**Issue by yrbhan** [karpathy/neuraltalk2#65]
I have followed all the steps and installed all dependencies required for neuraltalk2.
while running eval.lua 

$ th eval.lua -model /home/yash/pretrainedmodel/model_id1-501-1448236541.t7 -image_folder /home/yash/sample/ -num_images 2 
/home/yash/torch/install/bin/luajit: /home/yash/torch/install/share/lua/5.1/trepl/init.lua:383: /home/yash/torch/install/share/lua/5.1/loadcaffe/ffi.lua:10: /home/yash/torch/install/lib/lua/5.1/libloadcaffe.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameEv
stack traceback:
	[C]: in function 'error'
	/home/yash/torch/install/share/lua/5.1/trepl/init.lua:383: in function 'require'
	eval.lua:5: in main chunk
	[C]: in function 'dofile'
	...yash/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405d70

Am getting this error, any idea of what I am doing wrong?

Many thanks in advance for your help.
![screenshot from 2016-02-03 16-55-10](https://cloud.githubusercontent.com/assets/17044579/12781143/95c6d11e-ca98-11e5-90af-22abdbfcb17b.png)

**Comment by tunguz** [comment]
I am now trying to run it, and I am getting the same error. I've looked everywhere, but no solution seems to work for me.
