### ISSUE TITLE
How does neuraltalk2 extract regions fron image?

### ISSUE THREAD

**Issue by CDLuminate** [karpathy/neuraltalk2#74]
I don't find the code part corresponding to *R-CNN* or *region proposal* in `neuraltalk2` so I'm confused.

1. how does it propose image region? where is it located?
```
246   local feats = protos.cnn:forward(data.images)
```
2. how does it extract feature from regions?

Thank you.

**Comment by karpathy** [comment]
There are no regions involved anywhere in NeuralTalk2. This is all on full image level.

**Comment by CDLuminate** [comment]
Well thanks!

**Comment by CDLuminate** [comment]
Uh... I'm sorry but encountered the same problem again in `neuraltalk` (not 2), could you please provide some hints on it? will be appreciated.

**Comment by liuchang8am** [comment]
@CDLuminate in neuraltalk there's also no R-CNN. It's also on full image.
