### ISSUE TITLE
Using another CNN feature extractor

### ISSUE THREAD

**Issue by cuongduc** [karpathy/neuraltalk2#79]
I'm wondering what is the meaning of `layer_num` and `encoding_size` inside `net_utils.build_cnn`.
If I dont' want to use VGG-16 feature extractor, what should I do, I guess that I have to rewrite `net_utils.build_cnn`, right?

**Comment by liuchang8am** [comment]
I think the `layer_num` means to extract the fc7 layer outputs from the vgg16 network. The `encoding_size` means mapping the image 4096 vgg feature vector to, say 512 hidden space, thus LSTM can work in the space between the image and the words. And yes, if you want to use another feature extractor, you need to rewrite the `net_utils.build_cnn` function. Given a pretrained caffe model, you can load it to torch using [https://github.com/szagoruyko/loadcaffe](_loadcaffe_); you may also train the model from scratch by adding up the layers, using nn.Sequential(). Hope it helps.

**Comment by cuongduc** [comment]
@liuchang8am OK. Thanks for your help. I will try!

**Comment by cuongduc** [comment]
@liuchang8am I have successfully trained the model with AlexNet as a image feature extractor. And the results are expectedly worse than VGG.
