### ISSUE TITLE
[CaptureDelegate doFireTimer:]: unrecognized selector sent to instance 0x7fe0a2cb8820

### ISSUE THREAD

**Issue by jerryli1981** [karpathy/neuraltalk2#85]
Hi,
I got a wired issue on my mac with cpu model. The demo can last less then 30 secs. then this error occurs. The command I use is
th videocaptioning.lua -model ./model/model_id1-501-1448236541.t7_cpu.t7 
###
a man wearing a tie and a shirt and tie	
a man wearing a tie and a shirt	
Camera dropped frame!
Camera dropped frame!
a man wearing a hat and a tie	
a man wearing a tie and a hat	
a woman in a dress shirt and tie is holding a cell phone	
a man wearing a tie and a hat	
a man wearing a tie and a hat	
Camera dropped frame!
a man wearing a tie and a hat	
a woman in a dress shirt and tie is holding a cell phone	
Camera dropped frame!
a man wearing a tie and a hat	
a man wearing a tie and a hat	
Camera dropped frame!
a man wearing a tie and a shirt and tie	
a man wearing a tie and a hat	
2016-03-23 10:54:59.843 luajit[55282:2431233] -[CaptureDelegate doFireTimer:]: unrecognized selector sent to instance 0x7fe0a2cb8820
Cleaned up camera.
/Users/peng/torch/install/bin/luajit: C++ exception
##

**Comment by awal2** [comment]
Hey Jerry, how did you fix this? I'm having the same problem today
