### ISSUE TITLE
Problem: Same captions for every images

### ISSUE THREAD

**Issue by cuongduc** [karpathy/neuraltalk2#86]
I have trained the model with default  settings. The training has gone though roughly 35000 iterations (the latest checkpoint was created at iteration 12500). The achieved BLUE-1 was 0.468 and CIDEr was 0.65. However, when I tried to run `eval.lua` on the checkpoint model, it just gave the same caption no matter what image I fed in. **"a man in a suit and tie standing next to a woman"** 

Have anyone faced this problem? Is the reason that I need more patience and wait for longer training?
I trained the model on a Tesla K80, and it tooks about 3.5 hours to get through 35k iterations on MSCOCO dataset.

**Comment by ZhangChenyang** [comment]
Wait more iterations (about 50K to 100K) or tune your learning rate higher.

**Comment by cuongduc** [comment]
@ZhangChenyang OK. I've got the point. Thank you
