### ISSUE TITLE
MAC OSX 10.11 - eva.lua does not work

### ISSUE THREAD

**Issue by n0xi** [karpathy/neuraltalk2#88]
Hi,
I would like to test the neuraltalk2 on my macbook pro; and when i try to execute eval.lua i have this error message; and i don't know how can i fix it ... 

Any solution ?? 

cheers :)

```
th eval.lua -model /Users/n0xi/Downloads/test-img/model_id1-501-1448236541.t7 -image_folder /Users/n0xi/Downloads/test-img/ -num_images 10
/Users/n0xi/torch/install/bin/luajit: cannot open eval.lua: No such file or directory
stack traceback:
	[C]: in function 'dofile'
	...n0xi/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x010b23bbc0

```

**Comment by cjds** [comment]
Are you in the correct directory? I've tested `eval.lua` on my Mac and it ran fine

**Comment by n0xi** [comment]
i retry later with clean install :)
