### ISSUE TITLE
attempt to index upvalue 'C' (a nil value)

### ISSUE THREAD

**Issue by arvind2505** [karpathy/neuraltalk2#97]
Anyone suggestions on fixing this error? Thanks!
DataLoader loading json file: 	coco/cocotalk.json	
vocab size is 9567	
DataLoader loading h5 file: 	coco/cocotalk.h5	
read 123287 images of size 3x256x256	
max sequence length in data is 16	
assigned 113287 images to split train	
assigned 5000 images to split val	
assigned 5000 images to split test	
libprotobuf WARNING google/protobuf/io/coded_stream.cc:478] Reading dangerously large protocol message.  If the message turns out to be larger than 1073741824 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
Successfully loaded model/VGG_ILSVRC_16_layers.caffemodel
conv1_1: 64 3 3 3
conv1_2: 64 64 3 3
conv2_1: 128 64 3 3
conv2_2: 128 128 3 3
conv3_1: 256 128 3 3
conv3_2: 256 256 3 3
conv3_3: 256 256 3 3
conv4_1: 512 256 3 3
conv4_2: 512 512 3 3
conv4_3: 512 512 3 3
conv5_1: 512 512 3 3
conv5_2: 512 512 3 3
conv5_3: 512 512 3 3
fc6: 1 1 25088 4096
fc7: 1 1 4096 4096
fc8: 1 1 4096 1000
converting first layer conv filters from BGR to RGB...	
total number of parameters in LM: 	11908448	
total number of parameters in CNN: 	136358208	
constructing clones inside the LanguageModel	
/usr/local/torch/install/bin/luajit: /usr/local/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 1 module of nn.Sequential:
/usr/local/torch/install/share/lua/5.1/cudnn/init.lua:53: attempt to index upvalue 'C' (a nil value)
stack traceback:
	/usr/local/torch/install/share/lua/5.1/cudnn/init.lua:53: in function 'errcheck'
	...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:41: in function 'resetWeightDescriptors'
	...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:348: in function <...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:347>
	[C]: in function 'xpcall'
	/usr/local/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/usr/local/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	train.lua:246: in function 'lossFun'
	train.lua:297: in main chunk
	[C]: in function 'dofile'
	...ocal/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405800

WARNING: If you see a stack trace below, it doesn't point to the place where this error occured. Please use only the one above.
stack traceback:
	[C]: in function 'error'
	/usr/local/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
	/usr/local/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	train.lua:246: in function 'lossFun'
	train.lua:297: in main chunk
	[C]: in function 'dofile'
	...ocal/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405800

**Comment by AdityaChaganti** [comment]
@arvind2505 Did you figure this out?
